### ISSUE TITLE
角色成就

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/cj#27]
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/8476969/205439130-003129d0-1be2-4565-a0cb-0deb597074eb.png">

比如，切到怀旧服
我先登录我自己的号

然后退出，我又登成公号。

在公号就会还显示了角色，且报错！

**Comment by Kaviilee** [comment]
角色信息存在了 sessionStorage，无法判定登出逻辑
