### ISSUE TITLE
成就相关

### ISSUE THREAD

**Issue by Kaviilee** [JX3BOX/cj#28]
<img width="702" alt="image" src="https://user-images.githubusercontent.com/8476969/206090553-bb6525bf-8c14-4321-8911-3ffe9a27973f.png">

这个之前苦瓜是有的

- [ ] 已完成

![image](https://user-images.githubusercontent.com/25825282/205977960-0db2d51b-c802-4649-94d4-b22781a4ecd8.png)

----------

- [ ] 已完成

**Comment by iRuxu** [comment]
<img width="700" alt="image" src="https://user-images.githubusercontent.com/8476969/206090597-f6dd4825-dd99-4c04-950a-cd6fe5aa45a2.png">

这个苦瓜是按地图来的，看看应该是可以匹配出来
接口是 https://helper.jx3box.com/api/achievements?dungeon_name=%E8%A5%BF%E6%B4%A5%E6%B8%A1&page=1&limit=15&client=std

- [ ] 已完成
